src/pages/shop/GotchaSection.tsx

- 뽑기 후 포인트 내려가지 않는 문제 수정 -> 캐시 날리기

뽑기 후 포인트 내려가지 않는 문제 수정

---

src/components/ProductTable/ShopTableBackground.tsx
src/pages/shop/GotchaSection.tsx
src/pages/shop/SellSection/PetList.tsx
src/pages/shop/SellSection/index.tsx
src/pages/shop/index.page.tsx

- sell list에서서 페르소나가 많을 경우 스크롤이 될 수 있도록 하였어요. 
- sell list 오른쪽 빈공간 제거
- shop table background height fix

fix : "내 펫이 많아지면 화면을 넘어가요" 

---

.github/CODEOWNERS
.github/auto_assign.yml
.husky/pre-commit
package.json

husky, codeowners, auto-assign 점검 및 적용

---

apps/web/next.config.mjs

fix: delete output where next config

---

turbo.json

feat: append vercel dir at output of turbo build

---

apps/web/package.json

fix: delete asterisk versioning at web

---

apps/web/src/app/jwt/page.tsx

- 로그인 부분인 jwt 페이지에서 넘어가지 않아 확인해보니 next/router 문제여서 빠르게 수정하였습니다.

hotfix: next router error hotfix

---

.github/CODEOWNERS

code owner 수정

---

apps/web/src/apis/auctions/useGetPersonaTypes.ts
apps/web/src/app/shop/HistoryTable.tsx
apps/web/src/app/shop/ProductTable.tsx
apps/web/src/app/shop/Search/index.tsx
apps/web/src/app/shop/Tab.tsx
apps/web/src/app/shop/page.tsx
apps/web/src/components/Modal/Modal.tsx

- 상점 페이지에서 원하는 펫을 검색할 수 있는 기능을 추가하였어요. 
- 디자인 리뉴얼을 할 텐데 .. 리팩토링을 하는게 좋을까? 라는 생각이 들어 아직 안했는데 조금이라도 정리해보려고합니다. (다른 PR에서!)

Persona Search 기능 추가

---

apps/web/src/components/ClientProvider.tsx

- 제 곧 내
- 왼쪽 하아아단을 보면 세미콜론이 하나 있어요... 제거했습니다

fix: 알수없는 세미콜론 제거

---

apps/web/src/components/FeedBack/FeedBack.tsx
apps/web/src/components/Layout/Header.tsx

fix: typo and style

---

apps/web/src/app/shop/GotchaSection.tsx

close https://github.com/git-goods/gitanimals/issues/86

fix: gotcha button size and position

---

.github/labeler.yml

ci: append area api label

---

apps/web/src/app/shop/ProductTable.tsx
apps/web/src/app/shop/Search/index.tsx
apps/web/src/components/ClientProvider.tsx

fix https://github.com/git-goods/gitanimals/issues/85
- 동물 선택 시 페이지네이션 초기화 안됨 4c8eac83cd96d262f067bc7b9f8433e60915c47d
- 스낵바 프로바이더 적용 안됨 7c2e554782a3d4b8a50694560b6294819a8d46fd
- 동물 선택 모달에서 아래 잘리는 문제 10f4f68f268c91c8b3f1f8af94bfac2e7f38deed

fix: 동물 선택 페이지네이션, 동물 선택 스크롤, 스낵바 버그

---

.github/labeler.yml

- `area: UI`, `area: Utils` 추가

ci: more labeler

---

packages/ui/panda/src/theme/semanticTokens.ts
packages/ui/panda/src/theme/tokens.ts

refactor: 토큰 선언 시 제공되는 api 사용하기

---

.vscode/settings.json
packages/ui/panda/package.json
packages/ui/panda/src/theme/semanticTokens.ts
packages/ui/panda/src/theme/tokens.ts
packages/ui/panda/tsconfig.lint.json
packages/util/typescript/.eslintrc.js
packages/util/typescript/package.json
packages/util/typescript/src/array/includes.ts
packages/util/typescript/src/array/index.ts
packages/util/typescript/src/index.ts
packages/util/typescript/src/object/index.ts
packages/util/typescript/src/object/keys.ts
packages/util/typescript/tsconfig.json
pnpm-lock.yaml
pnpm-workspace.yaml

- 타입스크립트 관련 유틸이 있게 될 패키지를 만들었어요
- token을 생성하는 부분에 적용했어용

feat: `@gitanimals/util-typescript`

---

.vscode/settings.json
packages/api/src/_instance/safe.ts
packages/api/src/user/getUser.ts

close #66 
- safePost, safeDel 등 각 메소드 별로 만들 수 있는 팩토리 함수를 두었는데, 아직 타입 추론에 실패해서 ... 일단 safeGet만 만들었어용

api with safeParse util

---

apps/web/panda.config.ts
apps/web/src/app/Welcome.tsx
packages/ui/panda/panda.config.ts
packages/ui/panda/src/theme/index.ts
packages/ui/panda/src/theme/textStyles.ts

Text Style 상수 -> panda text style 알고리즘
- reduce를 이용하여 panda text style에서 필요한 객체 형식으로 변경하는 코드를 구현하였어요. 
- welcome page에 임시로 잘 변환되었는지 확인하는 console을 찍어두었습니다. 
- 이 방식이 괜찮다면 convert 함수를 만들어 사용하면 될 것 같습니다.

Text Style 상수 -> panda text style 알고리즘

---

apps/web/src/apis/github/usePostIssue.ts
apps/web/src/components/FeedBack/FeedBack.constants.tsx
apps/web/src/components/FeedBack/FeedBack.tsx

- @devxb 이가 재촉한(?) 이슈입니당. 
- 빠른 머지 가시죠

fix: auto post issue repo 변경

---

apps/web/src/lib/gtag.ts

dev 환경에서 gtag error fix

---

apps/web/src/app/CheckTime.tsx
apps/web/src/app/Welcome.tsx
apps/web/src/app/api/oauth/route.ts
apps/web/src/app/page.tsx
apps/web/src/components/LoginButton.tsx

서버 점검 시간 안내 추가

---

apps/admin/app/routes/shop.drop-pet.tsx
apps/web/src/app/landing/AvailablePetSection/AnimalSlider.tsx
apps/web/src/app/landing/AvailablePetSection/AvailablePetSection.tsx
apps/web/src/hooks/query/render/useGetAllPersona.ts
packages/api/src/render/getAllMyPets.ts
packages/api/src/render/getAllPersona.ts
packages/api/src/render/index.ts

랜딩페이지의 AnimalList API 연결

---

apps/admin/app/routes/shop.drop-pet.tsx
apps/web/src/app/landing/AvailablePetSection/AnimalSlider.tsx
apps/web/src/app/landing/AvailablePetSection/AvailablePetSection.tsx
apps/web/src/hooks/query/auction/useGetTotalProductCount.ts
apps/web/src/hooks/query/identity/useGetTotalIdentityUserCount.ts
apps/web/src/hooks/query/render/useGetAllPersona.ts
apps/web/src/hooks/query/render/useGetTotalPersonaCount.ts
apps/web/src/hooks/query/render/useGetTotalRenderUserCount.ts
packages/api/src/auction/getTotalProductCount.ts
packages/api/src/auction/index.ts
packages/api/src/identity/getTotalIdentityUserCount.ts
packages/api/src/identity/index.ts
packages/api/src/index.ts
packages/api/src/render/getAllMyPets.ts
packages/api/src/render/getAllPersona.ts
packages/api/src/render/getTotalPersonaCount.ts
packages/api/src/render/getTotalRenderUserCount.ts
packages/api/src/render/index.ts
pnpm-lock.yaml

- 밑과 같이 통계에 관련된 API를 연결하였어요. 
- 이후에 SSG로 받아올 수 있으면 좋을 것 같습니다.

통계 관련 API 연결

---

apps/web/src/app/shop/page.tsx

hotfix: bg color

---

apps/web/src/app/mypage/FarmType.tsx
apps/web/src/components/Gitanimals.tsx

https://github.com/user-attachments/assets/a2ab861a-2359-41e3-955f-0c7432bc349d
https://github.com/user-attachments/assets/e1ca7f66-6a38-406f-80ec-3debbeb47a02

refactor: farm 동물 선택 결과 즉시 반영

---

apps/web/src/app/shop/SellSection/SellInputRow.tsx
apps/web/src/app/shop/SellSection/index.tsx

close https://github.com/git-goods/gitanimals/issues/108
- price 최대 값 설정
- NaN 핸들링
- inputMode 설정

refactor: 상점 판매 로직 

---

apps/web/src/components/Layout/Header.tsx
apps/web/src/constants/outlink.ts

chore: update github url and open link with blank

---

apps/web/src/app/api/googleSheet/route.ts
apps/web/src/components/FeedBack/FeedBack.tsx
apps/web/src/constants/test.ts
apps/web/src/utils/log.ts

- sheet 로깅이 잘 되지 않는 것 같아. 로그 확인 로직을 넣었습니다.

feat: load 되었는지 체크하는 로직 추가

---

apps/web/src/components/FeedBack/FeedBack.tsx

- Landing 페이지의 Feedback Icon 겹친 문제 수정
- Feedback 로그인 안하고 하면 'not loggined'이라는 assigned 유저를 어사인 하면 터지는 문제 수정

Landing FeedBack Icon fix and Feedback Assigned fix

---

apps/web/src/apis/interceptor.ts
apps/web/src/app/api/auth/verifyToken/route.ts
apps/web/src/components/Layout/Header_v2.tsx
apps/web/src/components/LogoutButton.tsx
apps/web/src/middleware.ts
apps/web/src/utils/path.ts

- next-auth를 이용하여 로그인하는 기능만을 만들어두고, 로그아웃하는 기능을 만들지 않아 추가해두었습니다. 
- 액세스 토큰이 만료되었을 때 로그아웃을 시키고, 
- 미들웨어에서 매번 토큰 만료를 확인 후 세션 종료 or 이어가기를 진행합니다.

Auth 로그아웃 기능 추가

---

apps/web/package.json
apps/web/src/apis/github/core.ts
apps/web/src/apis/github/useCreateComment.ts
apps/web/src/apis/github/usePostFeedback.ts
apps/web/src/apis/github/usePostIssue.ts
apps/web/src/components/FeedbackForm.tsx
pnpm-lock.yaml

> 기존에 assigness 권한 이슈로 사용자가 피드백을 제출해도, issue에 등록되지 않았다 (로그 확인하다가 이슈 발견)
- octokit 이라는 라이브러리를 이용하여 Github Rest API 편하게 사용 (https://github.com/octokit/core.js#readme)
- github rest api를 이용하여 issue 생성 및 comment 생성
- 기존에 fetch를 이용하여 issue 생성하던 부분을 octkoit 라이브러리를 사용하는 방법으로 변경
- issue 생성 후 해당 issue에 comment를 달아 피드백을 제출한 사용자를 mention
- https://docs.github.com/ko/rest/issues?apiVersion=2022-11-28

Fix : Feedback Form 에러 수정

---

apps/web/src/apis/interceptor.ts
apps/web/src/components/FeedbackForm.tsx

- 리렌더링 이슈를 해결하기 위해 logout 로직을 임시 제거하였습니다.

hotfix: logout 로직 임시 변경

---

apps/web/src/apis/interceptor.ts
apps/web/src/apis/user/useGetUser.ts
apps/web/src/app/api/auth/signOut/route.ts
apps/web/src/auth.ts
apps/web/src/components/Layout/Header_v2.tsx
apps/web/src/components/Layout/LoginBtn.tsx

Hotfix : Auth Logout 로직 수정

---

apps/web/src/app/shop/SellSection/SellInputRow.tsx
apps/web/src/app/shop/SellSection/index.tsx
apps/web/src/components/Button/SmallButton.tsx
apps/web/src/components/ProductTable/ShopTableRowView.tsx

Panda css로 마이그레이션 (WIP)

---

apps/web/src/app/[locale]/error.tsx

feat: skip logging known error

---

apps/web/src/app/[locale]/shop/SellListSection/EditModal.tsx
packages/ui/panda/package.json
packages/ui/panda/src/components/Modal/Modal.tsx
packages/ui/panda/src/components/Modal/index.ts
packages/ui/panda/src/components/index.ts
pnpm-lock.yaml

edit 기능 부분에 지금 컨셉에 맞는 모달이 필요해 추가하였어요. 
디자인 시스템 등록을 하고 하기 보다는, 일단 만들고 추가하는게 좋을 것 같아 Modal Container만 ui pacakges에 만들고, edit modal쪽 핏만 맞추었습니다.

디자인 시스템 모달 임시 추가 (edit modal)

---

apps/web/panda.config.ts
apps/web/src/app/[locale]/shop/AuctionSection/HistoryTable.tsx
apps/web/src/app/[locale]/shop/AuctionSection/ProductTable.tsx
apps/web/src/app/[locale]/shop/SellListSection/EditModal.tsx
apps/web/src/app/[locale]/shop/SellListSection/index.tsx
apps/web/src/components/Modal/Modal.tsx
apps/web/src/components/ProductTable/ShopTableRowView.tsx
packages/ui/panda/package.json
packages/ui/panda/src/components/Modal/Modal.tsx
packages/ui/panda/src/components/Modal/index.ts
packages/ui/panda/src/components/index.ts
pnpm-lock.yaml

자잘한 수정건들이 있어 수정했어요. 
- 스켈레톤 UI를 추가해 화면 깜빡임을 줄였어요. 
- 페이지네이션을 통해 페이지를 바꿀 때 새 데이터를 가져오는 동안 깜빡이는 것을 줄이기 위해 `placeholderData`을 이용했어요. (이전에 성공한 쿼리의 데이터를 잠시 유지)

이런 저런 Shop 버그들 수정

---

apps/web/messages/en_US.json
apps/web/messages/ko_KR.json
apps/web/src/app/[locale]/shop/AuctionSection/HistoryTable.tsx
apps/web/src/app/[locale]/shop/AuctionSection/ProductTable.tsx
apps/web/src/app/[locale]/shop/AuctionSection/SellSection/SellInputRow.tsx
apps/web/src/app/[locale]/shop/PetGotcha/OnePet.tsx
apps/web/src/app/[locale]/shop/SearchOption/OrderTypeSelect.tsx
apps/web/src/app/[locale]/shop/SearchOption/SortDirectionSelect.tsx
apps/web/src/app/[locale]/shop/SellListSection/index.tsx
apps/web/src/app/[locale]/shop/page.tsx
apps/web/src/app/[locale]/shop/useSearchOptions.ts
apps/web/src/components/GlobalComponent/GlobalComponent.tsx
apps/web/src/components/Layout/DesktopGNB.tsx
apps/web/src/components/Layout/LanguageSelector.tsx
apps/web/src/components/Layout/menu.constants.tsx
apps/web/src/components/NoticeToast/NoticeToast.tsx
apps/web/src/components/NoticeToast/notice.tsx
apps/web/src/components/ProductTable/ShopTableRowView.tsx
apps/web/src/constants/action.ts
packages/util/common/src/index.ts
packages/util/common/src/string.ts

- 주로 한국어/영어 번역이 추가되었습니다. 
- 상점 리뉴얼 공지가 추가되었습니다. 
- 모바일 미지원 뷰가 추가되었습니다 (모바일화면에서만 보여짐)
- 상점 페이지에서 최신순 정렬이 기본이도록 변경되었습니다.

배포 전 마지막 fix

---

apps/web/src/app/[locale]/shop/PetGotcha/OnePet.tsx

feat: 뽑기 실패 에러 로깅 추가 정보

---

apps/web/messages/en_US.json
apps/web/messages/ko_KR.json
apps/web/src/app/[locale]/mypage/PersonaList.tsx
apps/web/src/app/[locale]/mypage/page.tsx
apps/web/src/components/NoticeToast/notice.tsx
packages/ui/panda/src/components/Banner/Banner.tsx
packages/ui/panda/src/components/Banner/cva.ts

마이페이지 리뉴얼 마이너 버그 픽스

---

apps/web/src/app/[locale]/mypage/my-pet/(merge)/MergePreview.tsx

fix: 머지 결과 계산 로직 변경

---

apps/web/src/app/[locale]/landing/AvailablePetSection/AvailablePetSection.tsx
packages/ui/panda/src/components/Button/Button.tsx

close https://github.com/git-goods/gitanimals/issues/170

fix: show more pet button to anchor

---

apps/web/src/app/[locale]/laboratory/page.tsx
apps/web/src/app/[locale]/laboratory/property-pet-sell/page.tsx

- 한번에 팔기 실험실 기능을 좀더 사용하기 좋게 개선하였습니다. 
- 주요 개선사항으로는 개수, 레벨별 정렬 그리고 판 이후 쿼리 무효화입니다

실험실 - 개수, 레벨별 정렬 및 쿼리 무효화 코드 추가

---

apps/web/src/app/[locale]/guild/SortSelect.tsx
apps/web/src/app/[locale]/guild/page.tsx
packages/ui/panda/src/components/Chip/CombineChip/CombineChip.tsx
packages/ui/panda/src/components/Chip/CombineChip/index.ts
packages/ui/panda/src/components/Chip/index.ts
packages/ui/panda/src/components/Select/index.ts
packages/ui/panda/src/components/index.ts

- Chip Component - combine 형태를 만들었습니다. Select와 같아서 이를 활용 + style을 조금 변경하였어요.
- 기존에 있던 Select를 deprecate시키고 제거할 예정입니다

feat: combine chip 컴포넌트 추가

---

apps/web/src/app/[locale]/shop/_auction/index.tsx

fix: 스타일 꺠지는거 수정

---

apps/web/src/app/[locale]/layout.tsx
apps/web/src/app/robots.ts
apps/web/src/app/sitemap.ts
apps/web/src/constants/config.ts
apps/web/src/i18n/routing.ts

- seo 개선을 위해 robot, sitemap 파일을 추가하였습니다. 
- 다국어가 지원될 수 있도록 고려해서 추가해두었어요

Robot.txt, sitemap 추가

---

apps/web/src/app/[locale]/landing/RankingSection/GameConsole/Joystick.tsx
apps/web/src/app/[locale]/landing/RankingSection/MobileGameConsole/MobileGameConsole.tsx
apps/web/src/app/[locale]/landing/RankingSection/RankingSection.tsx
apps/web/src/app/[locale]/landing/RankingSection/RankingTable.tsx
apps/web/src/app/[locale]/landing/RankingSection/TopPodium.tsx
apps/web/src/app/[locale]/shop/_auction/Tab.tsx
apps/web/src/app/[locale]/test/ranking/page.tsx

- ranking 기능의 mobile view를 추가하였습니다 
- tab의 경우 공통적으로 사용할 수 있도록 디자인 시스템에 추가 예정입니다.

Ranking Mobile 추가

---

apps/web/messages/en_US.json
apps/web/src/app/[locale]/guild/(subpage)/[id]/setting/GuidlInfoFormClient.tsx
apps/web/src/app/[locale]/guild/_components/GuildSearch.tsx
apps/web/src/app/[locale]/landing/ChoosePetSection/ChoosePetSection.tsx
apps/web/src/app/[locale]/landing/HavePetWaySection/HavePetWaySection.tsx
apps/web/src/app/[locale]/landing/MainSection/MainSection.tsx
apps/web/src/app/[locale]/mypage/my-pet/(merge)/MergePersona.tsx
apps/web/src/app/[locale]/mypage/my-pet/SelectedPetTable.tsx
apps/web/src/app/[locale]/mypage/page.tsx
apps/web/src/app/[locale]/shop/_auction/Tab.tsx
apps/web/src/app/[locale]/shop/_petGotcha/PetGotcha.tsx
apps/web/src/components/Global/FeedbackForm.tsx

chore: improve typo

---

apps/web/src/app/[locale]/shop/_background/BackgroundSection.tsx

fix: 배경 구매시 최신화
